### ISSUE TITLE
google-chrome-beta-54 doesnt distribute pepper-flash anymore 

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/chromium-pepper-flash#1]

**Comment by paulcarroty** [comment]
Wow, flash is dead for Chrom(ium)e? It's a good news.

**Comment by kuboosoft** [comment]
@sergiomb2 @paulcarroty no flash isn't  dead; read here https://blogs.adobe.com/flashplayer/2016/08/beta-news-flash-player-npapi-for-linux.html hahaha

**Comment by sergiomb2** [comment]
I didn't say that is dead I said that is not bundle in chrome anymore , 
https://bugs.chromium.org/p/chromium/issues/detail?id=645687#
https://support.google.com/chrome/answer/6213033?hl=en

Well I'd keep freshplayerplugin  solution, if Adobe rollback in his decisions, is not my problem , freshplayerplugin is working well , beta flash plugin I don't know and I don't want test it for them .

**Comment by sergiomb2** [comment]
https://get.adobe.com/flashplayer/otherversions/

https://fpdownload.adobe.com/pub/flashplayer/pdc/22.0.0.209/flash_player_ppapi_linux.x86_64.tar.gz

chrome-beta download version 23,0,0,162  ...

**Comment by kuboosoft** [comment]
Yes; we now can download the PPAPI version separately: https://blogs.adobe.com/flashplayer/2016/08/beta-news-flash-player-npapi-for-linux.html

**Comment by sergiomb2** [comment]
I don't found PPAPI for linux in http://labs.adobe.com/downloads/flashplayer.html , what is the link of PPAPI for linux ?

**Comment by kuboosoft** [comment]
@sergiomb2  don't worry, I will update next hours ;) I am writing in my phone.. I had some days playing it.

 PPAPI or Pepper Plugin API is an interface promoted by Chromium/Chrome team for browser plugins.

**Comment by sergiomb2** [comment]
Thanks ,   +License: LGPLv3 ? PPAPI is LGPLv3 ?

**Comment by kuboosoft** [comment]
@sergiomb2   Stranger no? yes  LGPLv3; but we need read about it. Why now "Adobe & Google", change your license; but the eulas are the same.

**Comment by sergiomb2** [comment]
I though though , and doesn't compute , if is LGPLv3 https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3) , we must have access to the source ! , and what means EULA: end user license agreement are the same , eula is the license , or not ?

**Comment by kuboosoft** [comment]
Yes, we need access to source code, today adobe published your [EULA](http://wwwimages.adobe.com/content/dam/acom/en/legal/licenses-terms/pdf/Flash_Player_23_0.pdf) and the "tar.gz" includes the LGPLv3. I do not understand why Adobe is now trying to revive completely flash with a license that will change the way you see flash.
